# Copyright (C) 2024 RTE
# Copyright (C) 2024 Red Hat, Inc.
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Ensure NetworkManager is started and enabled
  ansible.builtin.systemd:
    name: NetworkManager
    state: started
    enabled: true
  register: configure_seapath_distro_centos_nm_start

- name: Set need_reboot to true if NetworkManager state changed # noqa: no-handler
  ansible.builtin.set_fact:
    need_reboot: true # noqa: var-naming[no-role-prefix]
  when: configure_seapath_distro_centos_nm_start is changed
